services:
  codeguard:
    build: .
    user: root
    restart: always
    container_name: codeguard
    ports:
      - "8000:5000"
    environment:
      DATABASE_URL: mysql+pymysql://codeguard:codeguard@db/CodeGuard?charset=utf8mb4
      AWS_S3_ENDPOINT_URL: http://minio:9000
      AWS_S3_BUCKET: codeguard
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_S3_REGION: us-east-1
    volumes:
      - ./.data/instance:/opt/CodeGuard/instance
      - .:/opt/CodeGuard
    depends_on:
      - db
      - minio
    networks:
      default:
      internal:

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./conf/http.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - codeguard

  db:
    image: mariadb:11.6
    container_name: mariadb
    restart: always  # Changed from 'unless-stopped' to 'always'
    environment:
      MYSQL_ROOT_PASSWORD: codeguard
      MYSQL_DATABASE: CodeGuard
      MYSQL_USER: codeguard
      MYSQL_PASSWORD: codeguard
    volumes:
      - ./.data/mariadb:/var/lib/mysql  # Host Directory : Container Directory
    networks:
      internal:

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    container_name: minio
    restart: always  # Changed from 'unless-stopped' to 'always'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      internal:
    volumes:
      - ./.data/minio:/data  # Host Directory : Container Directory
    command: server /data --console-address ":9001"

# No need to define external volumes since we're using host directories
networks:
  default:
  internal:
    internal: true