"""Create Unique constraints 

Revision ID: 00d29d278dfa
Revises: cbae9d741ee1
Create Date: 2025-01-10 13:02:38.597185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d29d278dfa'
down_revision = 'cbae9d741ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_duplicate_contents', ['module_id', 'order'])

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_duplicate_modules', ['course_id', 'order'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint('uq_duplicate_modules', type_='unique')

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_constraint('uq_duplicate_contents', type_='unique')

    # ### end Alembic commands ###
