"""Added status to enrollments, enrollments_modules, users_contents

Revision ID: 05ab061760c7
Revises: e7f175a32cd8
Create Date: 2025-01-25 01:39:50.280649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05ab061760c7'
down_revision = 'e7f175a32cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enrollment_module_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'STARTED', 'COMPLETE', name='completionstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('option_selected', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['enrollment_module_id'], ['enrollments_modules.id'], ),
    sa.ForeignKeyConstraint(['option_selected'], ['options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_module_id', 'content_id', name='uq_content_users')
    )
    with op.batch_alter_table('users_challenges', schema=None) as batch_op:
        batch_op.drop_constraint('fk_enrollment_module_id', type_='foreignkey')
        batch_op.drop_constraint('fk_challenge_id', type_='foreignkey')
        batch_op.drop_index('uq_challenge_users')

    op.drop_table('users_challenges')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('NOT_STARTED', 'STARTED', 'COMPLETE', name='completionstatus'), nullable=False))

    with op.batch_alter_table('enrollments_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('NOT_STARTED', 'STARTED', 'COMPLETE', name='completionstatus'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments_modules', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.create_table('users_challenges',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('enrollment_module_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('challenge_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('isComplete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('attempts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('option_selected', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['contents.id'], name='users_challenges_ibfk_1'),
    sa.ForeignKeyConstraint(['enrollment_module_id'], ['enrollments_modules.id'], name='users_challenges_ibfk_2'),
    sa.ForeignKeyConstraint(['option_selected'], ['options.id'], name='users_challenges_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users_challenges', schema=None) as batch_op:
        batch_op.create_index('uq_challenge_users', ['enrollment_module_id', 'challenge_id'], unique=True)

    op.drop_table('users_contents')
    # ### end Alembic commands ###
