"""Update ExamsResults

Revision ID: 0a76a6dcf72b
Revises: 610f018e9a25
Create Date: 2025-03-04 18:01:42.873769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a76a6dcf72b'
down_revision = '610f018e9a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams_results', schema=None) as batch_op:
        batch_op.alter_column('exam_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams_results', schema=None) as batch_op:
        batch_op.alter_column('exam_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
