"""Added users_challenges table

Revision ID: 0d58eb6b0e3e
Revises: e8bb9fc0cb82
Create Date: 2025-01-16 05:56:06.329712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d58eb6b0e3e'
down_revision = 'e8bb9fc0cb82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_challenges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enrollment_module_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('isComplete', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['enrollment_module_id'], ['enrollments_modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_module_id', 'challenge_id', name='uq_challenge_users')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_challenges')
    # ### end Alembic commands ###
