"""empty message

Revision ID: 29b0f67983b2
Revises: 8b37c3835953
Create Date: 2025-01-07 17:03:07.402452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b0f67983b2'
down_revision = '8b37c3835953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
