"""Added Correctness to users_contents

Revision ID: 4d32e1aeb472
Revises: 05ab061760c7
Create Date: 2025-02-06 03:40:41.467158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d32e1aeb472'
down_revision = '05ab061760c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_contents', schema=None) as batch_op:
        batch_op.drop_column('correct')

    # ### end Alembic commands ###
