"""empty message

Revision ID: 51cacd763573
Revises: 89286b5cd348
Create Date: 2025-01-08 18:25:09.451123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51cacd763573'
down_revision = '89286b5cd348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('content_body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id')
    )
    op.drop_table('materials')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint('enrollments_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('enrollments_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=80), nullable=False))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('content_id', sa.Integer(), nullable=False))
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint('questions_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exams', ['exam_id'], ['id'])
        batch_op.create_foreign_key(None, 'contents', ['content_id'], ['id'])
        batch_op.drop_column('order')
        batch_op.drop_column('image')
        batch_op.drop_column('category')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('image', sa.BLOB(), nullable=False))
        batch_op.add_column(sa.Column('order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('questions_ibfk_1', 'courses', ['course_id'], ['id'])
        batch_op.alter_column('code',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.drop_column('content_id')
        batch_op.drop_column('exam_id')

    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('enrollments_ibfk_1', 'courses', ['course_id'], ['id'])
        batch_op.create_foreign_key('enrollments_ibfk_2', 'users', ['user_id'], ['id'])

    op.create_table('materials',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('material_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('image', sa.BLOB(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='materials_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('images')
    op.drop_table('contents')
    op.drop_table('modules')
    op.drop_table('exams')
    # ### end Alembic commands ###
