"""Add column for Course and Content Images

Revision ID: 5fcedf37ec92
Revises: ba08728def15
Create Date: 2025-01-11 15:52:30.605645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fcedf37ec92'
down_revision = 'ba08728def15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('new_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.alter_column('content_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.create_unique_constraint('uq_course', ['course_id'])
        batch_op.create_foreign_key('course_id', 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint('course_id', type_='foreignkey')
        batch_op.drop_constraint('uq_course', type_='unique')
        batch_op.alter_column('content_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('course_id')
        batch_op.drop_column('new_filename')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
