"""Removed ondelete rules on columns

Revision ID: 610f018e9a25
Revises: 475bf16c7265
Create Date: 2025-03-04 09:05:35.334909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610f018e9a25'
down_revision = '475bf16c7265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_constraint('contents_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'modules', ['module_id'], ['id'])

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint('enrollments_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('enrollments_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('enrollments_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'exams', ['exam_id'], ['id'])

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint('modules_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('modules_ibfk_1', 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('enrollments_ibfk_1', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('enrollments_ibfk_3', 'exams', ['exam_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('enrollments_ibfk_2', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('contents_ibfk_1', 'modules', ['module_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
