"""empty message

Revision ID: 7274fb680753
Revises: 8e7313d1d358
Create Date: 2025-01-10 02:57:25.334835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7274fb680753'
down_revision = '8e7313d1d358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(display_width=11),
               type_=CodeGuard.models.CourseStatus(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=CodeGuard.models.CourseStatus(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    # ### end Alembic commands ###
