"""Create enrollment_modules

Revision ID: 73299c3711e1
Revises: f77cb4e4baf3
Create Date: 2025-01-12 14:01:02.340334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73299c3711e1'
down_revision = 'f77cb4e4baf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments_modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'module_id', name='uq_duplicate_progress')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments_modules')
    # ### end Alembic commands ###
