"""empty message

Revision ID: 76ad2dbf9107
Revises: 822f8931d4f6
Create Date: 2025-01-07 16:16:22.401660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76ad2dbf9107'
down_revision = '822f8931d4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('last_enrolled_time',
               existing_type=mysql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('registration_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('registration_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('last_enrolled_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
