"""Add Exam Number Identifier

Revision ID: 88d952fdf914
Revises: 0a76a6dcf72b
Create Date: 2025-03-05 18:48:18.458213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d952fdf914'
down_revision = '0a76a6dcf72b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('exam_number')

    # ### end Alembic commands ###
