"""empty message

Revision ID: 89286b5cd348
Revises: 29b0f67983b2
Create Date: 2025-01-07 17:04:53.650494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89286b5cd348'
down_revision = '29b0f67983b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
