"""empty message

Revision ID: 8b37c3835953
Revises: d3f7f7689979
Create Date: 2025-01-07 16:21:18.833139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b37c3835953'
down_revision = 'd3f7f7689979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
