"""empty message

Revision ID: 8e7313d1d358
Revises: e277c9c75d76
Create Date: 2025-01-09 23:59:51.899450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7313d1d358'
down_revision = 'e277c9c75d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
