"""Alter Course, Exams, Questions table.

Revision ID: 98db67ce0ce0
Revises: 31ddcf7a453f
Create Date: 2025-01-10 12:42:01.544506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98db67ce0ce0'
down_revision = '31ddcf7a453f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('question_text',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('question_text',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('duration',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.drop_column('course_id')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    # ### end Alembic commands ###
