"""Modified Exams Table and Enrollments for Exam

Revision ID: a2b825c1cc34
Revises: 4d32e1aeb472
Create Date: 2025-02-07 10:45:56.586156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b825c1cc34'
down_revision = '4d32e1aeb472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'exams', ['exam_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('exam_id')

    # ### end Alembic commands ###
