"""Added todo count in exams table

Revision ID: b15e25d6e19e
Revises: a4bef7cf5897
Create Date: 2025-02-16 00:17:01.300279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15e25d6e19e'
down_revision = 'a4bef7cf5897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('todo')

    # ### end Alembic commands ###
