"""empty message

Revision ID: b6843e98e64e
Revises: 51cacd763573
Create Date: 2025-01-08 18:26:16.074449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6843e98e64e'
down_revision = '51cacd763573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
