"""empty message

Revision ID: b783e6b87c0e
Revises: 5d71091bc94f
Create Date: 2025-01-10 03:45:20.359788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b783e6b87c0e'
down_revision = '5d71091bc94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.alter_column('content_body',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.alter_column('content_body',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
