"""Alter Enrollments for time

Revision ID: ba08728def15
Revises: 5552011de58c
Create Date: 2025-01-11 14:36:27.658345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba08728def15'
down_revision = '5552011de58c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('last_enrolled_time',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_enrolled_twice', ['user_id', 'course_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_enrolled_twice', type_='unique')
        batch_op.alter_column('last_enrolled_time',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
