"""empty message

Revision ID: c4823a69c146
Revises: 07cd36e27a49
Create Date: 2025-01-09 21:49:14.503929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4823a69c146'
down_revision = '07cd36e27a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('new_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_filename', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
