"""empty message

Revision ID: d3f7f7689979
Revises: bedbdc5fa782
Create Date: 2025-01-07 16:20:57.148367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f7f7689979'
down_revision = 'bedbdc5fa782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
