"""empty message

Revision ID: e277c9c75d76
Revises: c4823a69c146
Create Date: 2025-01-09 21:52:29.021314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e277c9c75d76'
down_revision = 'c4823a69c146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
