"""Added selected column for users_challenges table

Revision ID: e7f175a32cd8
Revises: 0d58eb6b0e3e
Create Date: 2025-01-16 14:32:18.494640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f175a32cd8'
down_revision = '0d58eb6b0e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_selected', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'options', ['option_selected'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_challenges', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('option_selected')

    # ### end Alembic commands ###
