"""Alter last_enrolled -> last_accessed

Revision ID: f77cb4e4baf3
Revises: 5fcedf37ec92
Create Date: 2025-01-12 04:42:26.295779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f77cb4e4baf3'
down_revision = '5fcedf37ec92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_accessed_time', sa.Time(), nullable=False))
        batch_op.drop_column('last_enrolled_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_enrolled_time', mysql.TIME(), nullable=False))
        batch_op.drop_column('last_accessed_time')

    # ### end Alembic commands ###
